#!/usr/bin/perl

use strict;
use warnings;

print "Content-Type: text/html; charset=utf-8\n\n";

print "<!DOCTYPE html>\n";
print "<html>\n";
print "<head>\n";
print "    <title>Class Schedule - Hogwarts</title>\n";
print "    <link rel=\"stylesheet\" href=\"style.css\">\n";
print "</head>\n";
print "<body>\n";
print "    <div class=\"header\">\n";
print "        <h1>Hogwarts Class Schedule</h1>\n";
print "        <p class=\"motto\">First Year Students</p>\n";
print "    </div>\n";
print "\n";
print "    <div class=\"content\">\n";
print "        <h2>Monday</h2>\n";
print "        <ul>\n";
print "            <li>09:00 - Transfiguration (Professor McGonagall)</li>\n";
print "            <li>11:00 - Charms (Professor Flitwick)</li>\n";
print "            <li>14:00 - Potions (Professor Snape)</li>\n";
print "        </ul>\n";
print "\n";
print "        <h2>Tuesday</h2>\n";
print "        <ul>\n";
print "            <li>09:00 - Defense Against the Dark Arts</li>\n";
print "            <li>11:00 - Herbology (Professor Sprout)</li>\n";
print "            <li>14:00 - History of Magic (Professor Binns)</li>\n";
print "        </ul>\n";
print "\n";
print "        <h2>Wednesday</h2>\n";
print "        <ul>\n";
print "            <li>09:00 - Astronomy (Evening Class - Midnight)</li>\n";
print "            <li>11:00 - Flying Lessons (Madam Hooch)</li>\n";
print "        </ul>\n";
print "\n";
print "        <h2>Thursday</h2>\n";
print "        <ul>\n";
print "            <li>09:00 - Potions (Professor Snape)</li>\n";
print "            <li>11:00 - Transfiguration (Professor McGonagall)</li>\n";
print "            <li>14:00 - Charms (Professor Flitwick)</li>\n";
print "        </ul>\n";
print "\n";
print "        <h2>Friday</h2>\n";
print "        <ul>\n";
print "            <li>09:00 - Defense Against the Dark Arts</li>\n";
print "            <li>11:00 - History of Magic (Professor Binns)</li>\n";
print "            <li>14:00 - Herbology (Professor Sprout)</li>\n";
print "        </ul>\n";
print "\n";
print "        <h3>Important Notes</h3>\n";
print "        <p>All students must arrive 5 minutes before class begins.</p>\n";
print "        <p>Wands are required for all practical lessons.</p>\n";
print "        <p><a href=\"/\">Return to Main Page</a></p>\n";
print "    </div>\n";
print "</body>\n";
print "</html>\n";
