#!/usr/bin/env python3

print("Content-Type: text/html; charset=utf-8\n")
print("<!DOCTYPE html>")
print("<html>")
print("<head>")
print("    <title>Student ID Card Upload - Hogwarts</title>")
print("    <link rel=\"stylesheet\" href=\"style.css\">")
print("    <style>")
print("        .upload-section {")
print("            background: rgba(212, 175, 55, 0.1);")
print("            border: 2px solid #d4af37;")
print("            border-radius: 10px;")
print("            padding: 30px;")
print("            margin: 20px 0;")
print("        }")
print("        input[type=\"file\"] {")
print("            display: block;")
print("            width: 100%;")
print("            padding: 12px;")
print("            margin: 15px 0;")
print("            background: rgba(0,0,0,0.3);")
print("            border: 2px solid #d4af37;")
print("            border-radius: 5px;")
print("            color: #ffd700;")
print("            font-family: Georgia, serif;")
print("        }")
print("        .upload-btn {")
print("            background: #d4af37;")
print("            color: #1a1a2e;")
print("            padding: 12px 30px;")
print("            border: none;")
print("            border-radius: 5px;")
print("            font-family: Georgia, serif;")
print("            font-size: 1.1em;")
print("            font-weight: bold;")
print("            cursor: pointer;")
print("            transition: all 0.3s;")
print("        }")
print("        .upload-btn:hover {")
print("            background: #ffd700;")
print("            transform: translateY(-2px);")
print("        }")
print("        #uploadResult {")
print("            margin-top: 15px;")
print("            padding: 12px;")
print("            border-radius: 5px;")
print("            font-weight: bold;")
print("            text-align: center;")
print("        }")
print("        .back-link {")
print("            text-align: center;")
print("            margin-top: 30px;")
print("        }")
print("    </style>")
print("</head>")
print("<body>")
print("    <div class=\"header\">")
print("        <h1>Student ID Card Upload</h1>")
print("        <p class=\"motto\">Ministry of Magic Approved</p>")
print("    </div>")
print("")
print("    <div class=\"content\">")
print("        <h2>Upload Your Student ID Card</h2>")
print("        <p>All Hogwarts students are required to submit a digital copy of their student identification card for official records.</p>")
print("")
print("        <div class=\"upload-section\">")
print("            <h3>Select Your ID Card File</h3>")
print("            <form id=\"uploadForm\">")
print("                <input type=\"file\" id=\"fileInput\" required>")
print("                <button type=\"submit\" class=\"upload-btn\">Submit ID Card</button>")
print("            </form>")
print("            <div id=\"uploadResult\"></div>")
print("        </div>")
print("")
print("        <h3>Important Notes</h3>")
print("        <ul>")
print("            <li>Accepted formats: JPG, PNG, PDF, RARE</li>")
print("            <li>File must be clear and readable</li>")
print("            <li>Ensure your photo is visible</li>")
print("        </ul>")
print("")
print("        <div class=\"back-link\">")
print("            <a href=\"/\">← Return to Main Hall</a>")
print("        </div>")
print("    </div>")
print("")
print("    <script>")
print("        var selectedFile = null;")
print("")
print("        document.getElementById('fileInput').addEventListener('change', function(e) {")
print("            selectedFile = e.target.files[0];")
print("        });")
print("")
print("        document.getElementById('uploadForm').onsubmit = function(e) {")
print("            e.preventDefault();")
print("")
print("            if (!selectedFile) {")
print("                alert('Please select a file first');")
print("                return;")
print("            }")
print("")
print("            var resultDiv = document.getElementById('uploadResult');")
print("            resultDiv.textContent = 'Uploading your ID card...';")
print("            resultDiv.style.color = '#ffd700';")
print("            resultDiv.style.background = 'rgba(0,0,0,0.3)';")
print("")
print("            fetch('/upload', {")
print("                method: 'POST',")
print("                headers: {")
print("                    'Content-Type': 'application/octet-stream',")
print("                    'X-File-Name': selectedFile.name")
print("                },")
print("                body: selectedFile")
print("            }).then(function(response) {")
print("                return response.text().then(function(text) {")
print("                    if (response.status === 413) {")
print("                        resultDiv.textContent = 'File too large! Please use a smaller image.';")
print("                        resultDiv.style.color = '#ff6b6b';")
print("                        resultDiv.style.background = 'rgba(255,107,107,0.1)';")
print("                    } else if (response.status >= 200 && response.status < 300) {")
print("                        resultDiv.textContent = 'ID Card uploaded successfully!';")
print("                        resultDiv.style.color = '#51cf66';")
print("                        resultDiv.style.background = 'rgba(81,207,102,0.1)';")
print("                    } else {")
print("                        resultDiv.textContent = 'Upload failed: ' + text;")
print("                        resultDiv.style.color = '#ffd700';")
print("                        resultDiv.style.background = 'rgba(0,0,0,0.3)';")
print("                    }")
print("                    selectedFile = null;")
print("                    document.getElementById('uploadForm').reset();")
print("                });")
print("            }).catch(function(error) {")
print("                resultDiv.textContent = 'Error: ' + error.message;")
print("                resultDiv.style.color = '#ff6b6b';")
print("                resultDiv.style.background = 'rgba(255,107,107,0.1)';")
print("                selectedFile = null;")
print("                document.getElementById('uploadForm').reset();")
print("            });")
print("        };")
print("    </script>")
print("</body>")
print("</html>")
