#!/usr/bin/perl

use strict;
use warnings;

print "Content-Type: text/html; charset=utf-8\n\n";

print "<!DOCTYPE html>\n";
print "<html>\n";
print "<head>\n";
print "    <title>School Rules - Hogwarts</title>\n";
print "    <link rel=\"stylesheet\" href=\"style.css\">\n";
print "</head>\n";
print "<body>\n";
print "    <div class=\"header\">\n";
print "        <h1>Hogwarts School Rules</h1>\n";
print "        <p class=\"motto\">Draco Dormiens Nunquam Titillandus</p>\n";
print "    </div>\n";
print "\n";
print "    <div class=\"content\">\n";
print "        <h2>General Conduct</h2>\n";
print "        <ul>\n";
print "            <li>Placing bottles containing liquids on the tables is strictly forbidden.</li>\n";
print "            <li>Students shall not leave the castle after hours without permission.</li>\n";
print "            <li>The Forbidden Forest is strictly off-limits to all students.</li>\n";
print "            <li>Magic should not be used in the corridors between classes.</li>\n";
print "            <li>Students must not enter the third-floor corridor on the right-hand side.</li>\n";
print "        </ul>\n";
print "\n";
print "        <h2>Academic Requirements</h2>\n";
print "        <ul>\n";
print "            <li>All homework must be submitted on time to the respective professor.</li>\n";
print "            <li>Students must attend all scheduled classes unless excused by the Hospital Wing.</li>\n";
print "            <li>The use of Self-Spelling or Auto-Answer Quills is strictly forbidden during examinations.</li>\n";
print "        </ul>\n";
print "\n";
print "        <h2>Safety Regulations</h2>\n";
print "        <ul>\n";
print "            <li>Flying is permitted only during supervised Flying lessons.</li>\n";
print "            <li>Dueling between students is prohibited outside of supervised clubs.</li>\n";
print "            <li>The use of Unforgivable Curses will result in immediate expulsion.</li>\n";
print "        </ul>\n";
print "\n";
print "        <h2>Dormitory Rules</h2>\n";
print "        <ul>\n";
print "            <li>Students must be in their dormitories by 10:00 PM on weekdays.</li>\n";
print "            <li>Members of other houses are not permitted in house dormitories.</li>\n";
print "            <li>Lights out at 10:30 PM sharp.</li>\n";
print "        </ul>\n";
print "\n";
print "        <h2>Meal Times</h2>\n";
print "        <ul>\n";
print "            <li>Breakfast: 7:30 - 8:50 AM</li>\n";
print "            <li>Lunch: 12:00 - 1:00 PM</li>\n";
print "            <li>Dinner: 7:00 - 8:00 PM</li>\n";
print "        </ul>\n";
print "\n";
print "        <h3>Important Notice</h3>\n";
print "        <p>Violation of these rules may result in detention, loss of house points, TIG or in severe cases, expulsion.</p>\n";
print "        <p>Headmaster: Albus Dumbledore<br>Deputy Headmistress: Minerva McGonagall</p>\n";
print "        <p><a href=\"/\">Return to Main Page</a></p>\n";
print "    </div>\n";
print "</body>\n";
print "</html>\n";
