#!/usr/bin/env python3

print("Content-Type: text/html; charset=utf-8\n")
print("<!DOCTYPE html>")
print("<html>")
print("<head>")
print("    <title>Test Suite - Hogwarts</title>")
print("    <link rel=\"stylesheet\" href=\"/style.css\">")
print("</head>")
print("<body>")
print("    <div class=\"header\">")
print("        <h1>Test Suite</h1>")
print("        <p class=\"motto\">Quality Assurance for Magical Web Servers</p>")
print("    </div>")
print("")
print("    <div class=\"content\">")
print("        <h2>Error Page Testing</h2>")
print("        <p>Test various HTTP error responses by clicking the links below.</p>")
print("")
print("        <h3>4xx - Client Errors</h3>")
print("        <ul>")
print("            <li><a href=\"/restricted/secret.txt\">403 Forbidden</a> - Access to restricted resource</li>")
print("            <li><a href=\"/nonexistent_file.txt\">404 Not Found</a> - Non-existent file</li>")
print("        </ul>")
print("")
print("        <h3>5xx - Server Errors</h3>")
print("        <ul>")
print("            <li><a href=\"/test/crash.py\">500 Internal Server Error</a> - CGI script crash</li>")
print("            <li><a href=\"/test/slow.py\">504 Gateway Timeout</a> - CGI timeout</li>")
print("        </ul>")
print("")
print("        <div class=\"back-link\" style=\"text-align: center; margin-top: 30px;\">")
print("            <a href=\"/\">← Return to Main Hall</a>")
print("        </div>")
print("    </div>")
print("</body>")
print("</html>")
